language: node_js
node_js:
  - 4.2
addons:
  sauce_connect:
    username: SAUCE_USERNAME
    access_key: SAUCE_ACCESS_KEY

before_install:
  - npm install
  - npm start & WEBPACK_SERVER_PID=$!
  - sleep 10 # give webpack some time to start

script:
  - npm run e2e:ci

after_script:
  - kill WEBPACK_SERVER_PID
